### ISSUE TITLE
Project Model

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#1]
Scaffold project model and link projects path in navigation. 

Attributes:
id:integer
name:string
description:text
description_de:text
link:string (link to github project page)

**Comment by mawiegand** [comment]
Are there any objections or improvement suggestions for the attributes? Otherwise I will scaffold the model like mentioned above. 
/cc @BluePanel/bluepanel-website-devs

**Comment by apollo7321** [comment]
Yes. description_de for German translation. And perhaps a way to contact the author?

**Comment by mawiegand** [comment]
OK, the German translation is a good idea. Contact is possible trough Github. If it's not enough, we could add a additional contact info later.

**Comment by apollo7321** [comment]
FULL ACK.
