### ISSUE TITLE
Design: Layout of index project view

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#16]
First layout of index project view.

**Comment by lhannigbrinck** [comment]
Eventually add a short description or preview description instead of the full description at the index project view.

**Comment by lhannigbrinck** [comment]
Short description added to the index project view, action buttons are still an issue on mobile devices because of the table structure of index project view and need to be fixed

**Comment by lhannigbrinck** [comment]
We decided to leave this at it's actual state, because there is no problem for visitors who are not logged in.
