### ISSUE TITLE
Allow HTML in articles?

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#18]
Should we allow **HTML** in articles through displaying the content with **[raw](http://apidock.com/rails/ActionView/Helpers/RawOutputHelper/raw)**?
Because only mods and admins will be able to create articles, there should be no problem with that. Or should we choose the save way and only allow **BB-Code** or parse the content? What do you think?

/cc @BluePanel/bluepanel-website-devs

**Comment by apollo7321** [comment]
Only BB-Code. Custom HTML or such stuff might break the design.

**Comment by mawiegand** [comment]
We could use [ruby-bbcode](https://github.com/veger/ruby-bbcode) oder [bb-ruby](https://github.com/cpjolicoeur/bb-ruby)

**Comment by apollo7321** [comment]
We should decide this on the next meeting.

**Comment by SStalker** [comment]
BB-Code should be enough.

**Comment by lhannigbrinck** [comment]
Personally i do not see a need for Custom HTML. BB-Code should be fine.

**Comment by mawiegand** [comment]
[bb-ruby](https://github.com/cpjolicoeur/bb-ruby) seems to be more flexible, because it is **extensible** and you can **_enable/disable_ specific BBCode-Tags** easily.

So [bb-ruby](https://github.com/cpjolicoeur/bb-ruby) would be the better choice or what do you think?

**Comment by mawiegand** [comment]
I used [bb-ruby](https://github.com/cpjolicoeur/bb-ruby) for fixing #33. If we want to switch to [ruby-bbcode](https://github.com/veger/ruby-bbcode) we could simply change the gem in the gemfile, because the method call is similar.

**If you want to switch between gems reopen this issue and comment!**
