### ISSUE TITLE
Disable registration? 

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#23]
Should we disable the registration?
There isn't any reason for a user registration atm or am I missing something?
If there is any reason for having users, like allowing comments in articles, we could re-enable it. 

/cc @BluePanel/bluepanel-website-devs

**Comment by apollo7321** [comment]
Agreed. We don't need it. We can add the users manually.

**Comment by SStalker** [comment]
Agreed too...

**Comment by lhannigbrinck** [comment]
Agreed.
