### ISSUE TITLE
Design: Fix CSS of GitHub activity feed on index page

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#29]
Header and footer of GitHub activity feed on index page are not displayed correctly!

**Comment by lhannigbrinck** [comment]
Now displayd correctly.

**Comment by lhannigbrinck** [comment]
Encounterd issues with windows Browser, especially with the scrollbar.
Tested a little and i think five displayed acivities should be enough in number and lenght of the activity log. 
What do you think about that?

**Comment by mkotzjan** [comment]
![screenshot_2015-03-20-11-43-59](https://cloud.githubusercontent.com/assets/8384904/6750046/aacfb790-cef6-11e4-8c97-88cef66fd46e.png)
Github feed on My Galaxy S3

**Comment by lhannigbrinck** [comment]
We decided to delete the activity log for now ...
It will probably be back in a later version, e.g. as something self made with the git-api..
