### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#46]
Add footer with copyright and Github link.

**Comment by apollo7321** [comment]
To my knowledge the copyright information is unnecessary. It does not exist in the German "Urheberrecht". The copyright information was historically needed in the USA and needed to be registered. However, according to German laws, which is our jurisdiction the copyright information is useless.

**Comment by mkotzjan** [comment]
But it doesn't hurt to have one, right?

**Comment by apollo7321** [comment]
It's ugly and unnecessary.

**Comment by lhannigbrinck** [comment]
But an impressum would be nice wouldn't it?
