### ISSUE TITLE
Can't run bundle install

### ISSUE THREAD

**Issue by apollo7321** [BluePanel/rails-website#51]
I can't run `bundle install` properly. It stops and shows an information: 

> Could not find highline-1.7.0 in any of the sources

Although the Gemfile doesn't specify a version number. I'll try to run the website with a specific Highline version.

**Comment by mawiegand** [comment]
Which Ruby version are you using? 2.1 or 2.2 as listed under system dependencies? 2.2 is highly recommended! 
Please add your full error log!

**Comment by apollo7321** [comment]
2.2. It doesn't have to do with the ruby version. The source for highline 1.7.0 was _removed_, see: https://rubygems.org/gems/highline/versions/1.7.0

There is no error log, only this one line on the command line.

**Comment by apollo7321** [comment]
It works with a modified Gemfile. I'll test if the Gem still works and push the changes if there's no problem.
