### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by mawiegand** [BluePanel/rails-website#7]
Decide what should be displayed on the index page.

**Comment by mawiegand** [comment]
We could display the activity log of our BluePanel organisation on Github and the latest articles. What do you think @BluePanel/bluepanel-website-devs?

**Comment by lhannigbrinck** [comment]
Activity log and latest articles should be fine.

**Comment by mawiegand** [comment]
Implemented latest articles (see #30) and GitHub activity feed (see #28).
If something else should be added, feel free to reopen this issue!
